version: '3.3'
services:
  web_dev:
    build: ./docker/nginx
    container_name: web_dev
    volumes:
      - ./app:/var/www/html
    working_dir: /etc/nginx
    links:
      - python_dev
      - mysql_dev
    ports:
      - 80:80
  python_dev:
    build: ./docker/python
    container_name: python_dev
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql_dev
  mysql_dev:
    build: ./docker/mysql
    container_name: mysql_dev
    ports:
      - 3306:3306
    volumes:
      - data-volume-dev:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=vzor_db
  frontend_dev:
    build: ./docker/frontend
    container_name: frontend_dev
    volumes:
      - ./app:/app
      - node-modules-dev:/app/node_modules
    working_dir: /app
    ports:
      - 3000:3000

volumes:
  data-volume-dev:
  node-modules-dev:
